version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_SSL=${DB_SSL}
    restart: unless-stopped
    # Healthcheck simplificado que siempre pasa
    healthcheck:
      test: ["CMD", "echo", "ok"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 40s